[dictionary]
words = "dict/jmdict-full.json.gz"
kanji = "dict/kanji.json"

[parser]
dictionary = "embedded://ipadic"
blacklist = "blacklist.txt"

[parser.filtering]
exclude_chars = ["ー", "〜"]

[parser.mapping]
Noun = [["名詞", "一般"], ["名詞", "サ変接続"]]
Verb = [["動詞", "自立"]]
Adjective = [["形容詞", "*"], ["名詞", "形容動詞語幹"]]
Misc = [["感動詞", "*"]]

[[decks]]
type = "jlpt"
name = "jlpt"
path ="decks/jlpt.json"

[[decks]]
type = "anki"
name = "日本語::Kaishi 1.5k"
word = "Word"
reading = "Word Reading"
meaning = "Word Meaning"

[anki]
url = "http://localhost:8765"

